#
#  Docker compose description
#  includes kafka + kafkaUI images and content-adm, currency and video services
#
networks:
  exchange-net:
    driver: bridge

services:
  kafka_broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: kafka-broker
    ports:
      - 9092:9092
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://kafka-broker:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-broker:29093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - exchange-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - 8088:8080
    depends_on:
      - kafka_broker
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-broker:9092
    networks:
      - exchange-net

  content-adm:
    build:
      context: ./content-adm
    ports:
      - "8080:8080"
    depends_on:
      - kafka_broker
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/postgres?currentSchema=deep2k
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-broker:9092
    networks:
      - exchange-net

  advertiser:
    build:
      context: ./advertiser
    ports:
      - "8081:8081"
    depends_on:
      - kafka_broker
      - content-adm
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-broker:9092
    networks:
      - exchange-net

  currency-monitor:
    build:
      context: ./currency-monitor
    ports:
      - "8082:8082"
    depends_on:
      - kafka_broker
      - content-adm
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-broker:9092
    networks:
      - exchange-net